backend:
  name: github
  repo: ruabien/astroship # Tên repository website của bạn
  branch: main
  base_url: https://decap-auth-ruabien.ruabien1504.workers.dev # <--- DÁN LINK WORKER VỪA THÀNH CÔNG VÀO ĐÂY
  auth_endpoint: auth

display_url: https://astroship-cuv.pages.dev
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "ebooks"
    label: "Ebooks"
    folder: "src/content/ebooks"
    create: true
    fields:
      - {label: "Tiêu đề", name: "title", widget: "string"}
      - {label: "Giá (VNĐ)", name: "price", widget: "number"}
      - {label: "Mô tả", name: "description", widget: "text"}
      - {label: "Ảnh bìa", name: "image", widget: "image"}
